{% set build = 0 %}
{% set name = "powerline-gitstatus" %}
{% set version = "1.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/jaspernbrouwer/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f1c1683d917e95c76bff1fa1e6ef64ad2463549ee246b29a72017184bfd040b3

build:
  noarch: python
  number: {{ build }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python
    - powerline-status

test:
  imports:
    - powerline_gitstatus

about:
  home: https://github.com/jaspernbrouwer/powerline-gitstatus/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Powerline segment for showing the status of a Git working copy

extra:
  recipe-maintainers:
    - lebedov
