travis:
  secure:
    BINSTAR_TOKEN: pazXa0F8Sa0aoCryj1L0SXAl7PkrCmRLpbBCqLOni4zy/IpTDBgvNZfBNP8nIgGU7IlGor+lRF17/PSVpOw7IgVkKE1zDyBn2JbOyfxkjs1XvVFe6qE04whEebLpLDkFwlKy6NVZlcLBIldnZTTNqOV0zb8mgqev8us3jCV967DY6KPlKKfeDMOJzBiEYy69V5SqI76jUGjCmhxtdj3tiJ0A+nFpj9xcORQNxdTIJCz36M2OLIzf3yNNfJz99qGw/9ku6lSxwNtkF/t4W2DzJd2HRyd4a+/B3qSawvAJhrJmfI5MURgjToXiXL4K6zW1qCajJGyeVUCL2rg2zxPHf0kT7Z3Nu7Zq61l5UfWLdf/BESspLZYMaw1j2rGFRNRkNp8UDUjgWXhpU655z/4I/XBLwIj+JpVAmsUUvUHrZFo7u5KEndBw5K6RXkk1GkYuRZ92BRON9Bwg+BjhHY+mEh/k/nNHyIhyK+07jzBkf2+e2FiJRDiM5p2PoolYo1xeid6GGLAMQxkM5IrJ+bj20xxFQmDYdScTl9eRIWvotStX8t3LBrZm9moyAeGTsT7qdzZUF+JSv1KPfHUGP0/bUUCzQOvQS4eSjbqhez83SjFQWd/I/xN9c/5R0KdjPpkSLnuAame8K31wpTBuxt53S0aMuGduEb0N5uCYlaaHyTY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
